/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ChemSafetyAsst;
import static spark.Spark.*;
import Chemical.Chemical;
import java.io.*;
import java.net.URI;
import java.net.http.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World! Test";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        HttpClient client = HttpClient.newBuilder().build();
        ObjectMapper objectMapper = new ObjectMapper();

        get("/chemicals", (req, res) -> {
            ArrayList<String> test = new ArrayList<String>();
            for(String param : req.queryParams()){
                System.out.println(param);
                for (String value : req.queryParamsValues(param)){
                    test.add((param + ": " + value));
                    HttpRequest cidRequest = HttpRequest.newBuilder()
                    .uri(
                        URI.create("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/"+value+"/cids/json")
                        ).build();
                    HttpResponse cidResponse;
                    try {
                        cidResponse = client.send(
                            cidRequest, HttpResponse.BodyHandlers.ofString()
                            );
                    } catch (IOException e) {
                        System.out.println("IO exception occurred");
                        throw new IOException("error in cidRequest");
                        // return "error";
                    }
                    System.out.println(cidResponse.body());
                };
            };
            return test;
        });
        
        get("/testrequest", (req, res) -> {
            HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create("https://pubchem.ncbi.nlm.nih.gov/rest/pug/substance/sid/53789435/synonyms/json"))
            .build();
            HttpResponse response;
            try {
                response = client.send(
                    request, HttpResponse.BodyHandlers.ofString()
                    );
            } catch (IOException e) {
                // gotBack = "?";
                System.out.println("IO exception occurred");
                return "error";
            }
            return response.body();
        });

        get("/hello", (req, res) -> "Hello World");
        get("/stop", (req, res) -> {
            stop();
            return "stopping";
        });
        get("/identifier/:id", (req, res)-> {
            Chemical c = new Chemical(req.params(":id"));
            return c.printIdentifier();
        });
    }
}
