/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package chem.safety.asst.backend;
package ChemSafetyAsst;

public class App {
    public String getGreeting() {
        return "Hello World! Test";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
